import colors from "./colors"

const pxToVw = (px) => `${(parseFloat(px) / 1440 * 100).toFixed(3)}vw`

const aboutData = [
    {
        type: "staff",
        name: "Scott Mueller",
        role: "Partner",
        bio: "Strategist, designer, and project manager always looking for intuitive, elegant solutions. He’s designed everything from logos and brands to software, tangible products, and actual physical communities. Consummate hobbyist and enthusiastic reader and activist.",
        image: "scott.jpeg",
        captionWidth: '18.23vw',
        captionHeight: '16.98vw',
        backgroundColor: colors.hkw.orange[300],
        color: colors.hkw.neutral.white,
    },
    {
        type: "trivia",
        text: "Celebrating 14 years in business!",
        index: 0,
        triviaBackgroundColor: colors.hkw.yellow[300],
        triviaTextColor: colors.hkw.neutral.black,
    },
    {
        type: "testimonial",
        name: "Melissa Huggins",
        role: "Executive Director at Spokane Arts",
        quote: "We can’t recommend HKW highly enough.",
        testimonialBackgroundColor: colors.hkw.blue[400],
        textColor: colors.hkw.blue[100],
        attrContainerColor: '#b8e6ff',
        attrBackgroundColor: '#050f44',
        attrTransform: 'rotate(2.697deg)',
        attrTextTransform: 'rotate(-8.85deg)',
        attrTextColor: '#B8E6FF',
        attrTextWidth: '9.653vw',
    },
    {
        type: "staff",
        name: "Geneva Kaiser",
        role: "Partner",
        bio: "Frontend developer, designer, writer, and problem solver. Drinks too much coffee. Avid bicyclist, reader, and crafter.",
        image: "geneva.jpeg",
        captionWidth: '15.52vw',
        captionHeight: '15.52vw',
        backgroundColor: colors.hkw.blue[400],
        color: colors.hkw.blue[100],
    },
    {
        type: "staff",
        name: "Gabi Castillo",
        role: "Retainer PM",
        bio: "Project manager and designer, fresh into the professional world. She is always learning and loves getting to know clients throughout the project process. In her free time, she’s an avid runner, coffee lover and outdoor enthusiast.",
        image: "gabi.jpeg",
        backgroundColor: colors.hkw.yellow[300],
        captionHeight: '19.47vw',
        captionWidth: '20.22vw',
        color: colors.hkw.blue[100],
    },
    {
        type: "testimonial",
        name: "Blaise Yen",
        role: "Digital Marketing Manager at Thermo Fisher",
        quote: "HKW understood our needs better than we did.",
        color: colors.hkw.neutral.white,
        left: '6.64vw',
        top: '11.59vw',
        testimonialBackgroundColor: colors.hkw.orange[300],
        testimonialLeft: '5.14vw',
        testimonialTop: '5.14vw',
        textMargin: '4.097vw 2.083vw 7.639vw 4.861vw',
        textColor: colors.hkw.neutral.white,
        textTransform: '',
        attrContainerColor: '#b8e6ff',
        attrContainerWidth: '20.12vw',
        attrContainerHeight: '13.69vw',
        attrWidth: '19.888vw',
        attrHeight: '13.33vw',
        attrClipPath: 'polygon(7% 14%, 70% 0, 100% 78%, 0 100%)',
        attrBackgroundColor: colors.hkw.orange[200],
        attrTransform: 'rotate(2.697deg)',
        attrTextTransform: 'rotate(-8.395deg)',
        textTop: '4.58vw',
        textLeft: '3.13vw',
        attrTextColor: colors.hkw.neutral.white,
        attrBottom: '4.86vw',
        attrRight: '-19.08vw',
    },
    {
        type: "trivia",
        text: "Proud to be 50% Woman Owned.",
        index: "1",
        triviaBackgroundColor: colors.hkw.blue[400],
        triviaClipPathWidth: '23.62vw',
        triviaClipPathHeight: '23.534vw',
        triviaTextWidth: '23.53vw',
        triviaTextColor: colors.hkw.neutral.black,
        triviaTextTop: '8.33vw',
        triviaTextLeft: '3.82vw',
    },
    {
        type: "staff",
        name: "Clare Kocheri",
        role: "Project Manager",
        bio: "Part writer, part manager, fully committed to project excellence. She loves discovering the words that capture a client’s identity, and then implementing the system that delivers those words to the public. Enthusiastic foodie, traveler, and people-watcher.",
        image: "clare.jpeg",
        captionWidth: '18.23vw',
        captionHeight: '16.98vw',
        backgroundColor: colors.hkw.red[300],
        captionClipPathTransform: 'rotate(24.419deg)',
        captionClipPath: ' polygon(0 18%, 82% 0, 100% 79%, 10% 100%)',
        captionClipPathHeight: '12.04vw',
        captionClipPathWidth: '14.55vw',
        infoWidth: '10.28vwx',
        color: colors.hkw.neutral.white,
        infoTransform: 'rotate(-24.419deg)',
    },
    {
        type: "testimonial",
        name: "Paul Sebastien",
        role: "CEO at Sqord",
        quote: "HKW was a real pleasure to work with.",
        color: colors.hkw.neutral.black,
        width: '32.42vw',
        height: '32.1vw',
        left: '24.72vw',
        top: '9.17vw',
        testimonialBackgroundColor: colors.hkw.yellow[300],
        testimonialWidth: '26.23vw',
        testimonialHeight: '28.75vw',
        testimonialTransform: '',
        testimonialClipPath: 'polygon(16% 0, 100% 12%, 84% 100%, 0 87%)',
        testimonialLeft: '6.81vw',
        testimonialTop: '4.76vw',
        textMargin: '4.097vw 2.083vw 7.639vw 4.861vw',
        textWidth: '12.36vw',
        textColor: colors.hkw.neutral.black,
        textTransform: '',
        attrContainerColor: '#b8e6ff',
        attrContainerWidth: '20.12vw',
        attrContainerHeight: '12.69vw',
        attrContainerBottom: '1.39vw',
        attrContainerLeft: '.13vw',
        attrWidth: '14.02vw',
        attrHeight: '14.02vw',
        attrClipPath: 'polygon(100% 0, 85% 50%, 100% 100%, 0 100%, 0 0)',
        attrBackgroundColor: colors.hkw.yellow[400],
        attrTransform: 'rotate(15deg)',
        attrTextTransform: 'rotate(-3deg)',
        textTop: '1.95vw',
        textLeft: '1.818vw',
        attrTextColor: colors.hkw.neutral.black,
        attrTextWidth: '8.976vw',
        // attrBottom: '-7.639vw',
        // attrRight: '-5.208vw',
        testimonialTextLeft: '-0.694vw',
        testimonialTextTop: '4.861vw',
    },
    {
        type: "testimonial",
        name: "Eben Cole",
        role: "Cole Music Co.",
        quote: "HKW has done wonders for my business.",
        color: colors.hkw.neutral.black,
        width: '29.432vw',
        height: '29.903vw',
        left: '15.813vw',
        top: '14.861vw',
        testimonialBackgroundColor: colors.hkw.red[500],
        testimonialWidth: '25.273vw',
        testimonialHeight: '27.775vw',
        testimonialTransform: 'rotate(-5.236deg',
        testimonialClipPath: 'polygon(0 14%, 84% 0, 100% 88%, 18% 100%)',
        testimonialLeft: '6.319vw',
        testimonialTop: '5.208vw',
        textMargin: '5.486vw 2.083vw 7.639vw 4.861vw',
        textWidth: '14.792vw',
        textColor: colors.hkw.neutral.black,
        textTransform: 'rotate(5.236deg',
        attrContainerBottom: '-3.616vw',
        attrContainerLeft: '4.167vw',
        attrWidth: '14.807vw',
        attrHeight: '11.054vw',
        attrClipPath: 'polygon(0 22%, 79% 0, 100% 73%, 10% 100%)',
        attrBackgroundColor: colors.hkw.red[300],
        attrTransform: 'rotate(11.542deg)',
        attrTextTransform: 'rotate(-11.542deg)',
        textTop: '3.889vw',
        textLeft: '2.608vw',
        attrTextColor: colors.hkw.neutral.white,
        attrTextWidth: '9.653vw',
        attrBottom: '-1.567vw',
        // attrRight: '-19.097vw',
        // testimonialTextLeft: '-0.694vw',
        // testimonialTextTop: '1.389vw',
    },
    {
        type: "staff",
        name: "Travis Irwin",
        role: "CMO",
        bio: "SEO marketer, strategic planner, and project leader, building brands for online success through innovative problem solving. Has developed multi-faceted digital marketing strategies across Fortune 100 companies, startups, and local businesses. Lover of coffee; travel enthusiast and sci-fi junkie.",
        image: "travis.png",
        containerWidth: '33.115vw',
        containerHeight: '33.681vw',
        imageWidth: '30.764vw',
        imageHeight: '33.681vw',
        transform: 'rotate(10deg) scale(1)',
        transformHover: 'rotate(0deg) scale(1.1)',
        // captionWidth: '18.23vw',
        // captionHeight: '16.983vw',
        backgroundColor: colors.hkw.blue[100],
        captionClipPathTransform: 'rotate(3.528deg)',
        captionClipPath: 'polygon(35% 0, 95% 15%, 100% 100%, 0 74%)',
        captionHeight: '13.338vw',
        captionWidth: '19.88vw',
        infoWidth: '10.279vw',
        color: colors.hkw.blue[500],
        infoTransform: 'rotate(-3.528deg)',
    },
    {
        type: "testimonial",
        name: "Blaise Yen 2",
        role: "Digital Marketing Manager at Thermo Fisher",
        quote: "HKW understood our needs better than we did.",
        color: colors.hkw.neutral.white,
        width: '33.52vw',
        height: '29.11vw',
        left: '6.638vw',
        top: '11.582vw',
        testimonialBackgroundColor: colors.hkw.orange[300],
        testimonialWidth: '24.018vw',
        testimonialHeight: '25.63vw',
        testimonialTransform: '',
        testimonialClipPath: 'polygon(13% 0, 100% 14%, 87% 100%, 0 87%)',
        testimonialLeft: '5.139vw',
        testimonialTop: '5.0vw',
        textMargin: '4.097vw 2.083vw 7.639vw 4.861vw',
        textWidth: '14.792vw',
        textColor: colors.hkw.neutral.white,
        textTransform: '',
        attrContainerColor: '#b8e6ff',
        attrContainerWidth: '20.117vw',
        attrContainerHeight: '13.694vw',
        attrContainerBottom: '0',
        attrContainerLeft: '0.139vw',
        attrWidth: '19.88vw',
        attrHeight: '13.338vw',
        attrClipPath: 'polygon(7% 14%, 70% 0, 100% 78%, 0 100%)',
        attrBackgroundColor: colors.hkw.orange[200],
        attrTransform: 'rotate(2.697deg)',
        attrTextTransform: 'rotate(-8.395deg)',
        textTop: '4.583vw',
        textLeft: '3.125vw',
        attrTextColor: colors.hkw.neutral.white,
        attrTextWidth: '12.569vw',
        attrBottom: '4.861vw',
        attrRight: '-19.097vw',
        testimonialTextLeft: '-0.694vw',
        testimonialTextTop: '1.389vw',
    },
    {
        type: "testimonial",
        name: "Julia Cohen Sebastien",
        role: "Co-Founder and CEO at Grayce",
        quote: "HKW has been an incredibly thoughtful partner.",
        color: colors.hkw.blue[100],
        width: '32.861vw',
        height: '33.651vw',
        left: '25.0vw',
        top: '20.833vw',
        testimonialBackgroundColor: colors.hkw.blue[400],
        testimonialWidth: '24.937vw',
        testimonialHeight: '26.34vw',
        testimonialTransform: 'rotate(-21.522deg',
        testimonialClipPath: 'polygon(15% 0, 100% 13%, 88% 100%, 0 88%)',
        testimonialLeft: '3.472vw',
        testimonialTop: '15.278vw',
        textMargin: '11.042vw 2.083vw 7.639vw 4.861vw',
        textWidth: '17.292vw',
        textColor: colors.hkw.blue[100],
        textTransform: 'rotate(21.522deg',
        attrContainerColor: '#b8e6ff',
        attrContainerWidth: '15.74vw',
        attrContainerHeight: '13.418vw',
        // attrContainerBottom: '0',
        // attrContainerLeft: '0.139vw',
        attrWidth: '15.158vw',
        attrHeight: '12.719vw',
        attrClipPath: 'polygon(0 20%, 87% 0, 100% 83%, 13% 100%)',
        attrBackgroundColor: '#050F44',
        attrTransform: 'rotate(2.697deg)',
        attrTextTransform: 'rotate(-10.697deg)',
        textTop: '-2.292vw',
        textLeft: '-3.472vw',
        attrTextColor: "B8E6FF",
        attrTextWidth: '10.892vw',
        attrBottom: '12.5vw',
        attrRight: '',
        // testimonialTextLeft: '-0.694vw',
        // testimonialTextTop: '1.389vw',
    },
    {
        type: "staff",
        name: "Stephen Okonkwo",
        role: "Designer",
        bio: "Designer with a natural passion for design and a firm grasp of design tools and techniques. He’s handled projects from brand identities to designing digital products. Avid reader and a fan of First Person Shooter video games.",
        image: "stephen.png",
        containerWidth: '38.334vw',
        containerHeight: '38.362vw',
        imageWidth: '34.47vw',
        imageHeight: '31.832vw',
        transform: 'rotate(13deg)',
        transformHover: 'rotate(0deg)',
        // captionWidth: '14.236vw',
        // captionHeight: '15.694vw',
        backgroundColor: colors.hkw.yellow[300],
        captionClipPathTransform: 'rotate(65.903deg)',
        captionClipPath: 'polygon(100% 0, 80% 50%, 100% 100%, 0 100%, 0 0)',
        captionClipPathWidth: '14.236vw',
        captionClipPathHeight: '15.694vw',
        infoWidth: '13.542vw',
        color: colors.hkw.neutral.black,
        infoTransform: 'rotate(-65.903deg)',
    },
    {
        type: "staff",
        name: "Adam Townsend",
        role: "Full Stack Dev",
        bio: "Adam Townsend is a problem solver at heart, and applies that passion through his work as a web developer.",
        image: "adam.png",
        containerWidth: '36.375vw',
        containerHeight: '31.463vw',
        imageHeight: '29.376vw',
        imageWidth: '24.564vw',
        transform: 'rotate(-5.131deg)',
        transformHover: 'rotate(0deg)',
        // captionWidth: '15.685vw',
        // captionHeight: '11.919vw',
        backgroundColor: colors.hkw.red[300],
        captionClipPathTransform: 'rotate(-11.149deg)',
        captionClipPath: 'polygon(17% 0, 100% 26%, 93% 100%, 0 74%)',
        // captionClipPathWidth:'15.685vw',
        // captionClipPathHeight: '11.919vw',
        infoWidth: '12.5vw',
        color: colors.hkw.neutral.white,
        infoTransform: 'rotate(11.149deg)',
    },
    { type: "testimonial", name: "Ryan Kerrigan", role: "Founder and Executive Director at Peak7", quote: "They were extremely quick and put out an incredible product.", color: colors.hkw.neutral.black, },
    { type: "testimonial", name: "Nancy Janzen", role: "CEO at Maplewood", quote: "We are grateful we selected HKW...", color: colors.hkw.neutral.black, },
    {
        type: "staff",
        name: "Jennifer Chang",
        role: "SEO Strategist",
        image: "jenn.png",
        bio: "Friendly SEO marketer passionate about helping businesses succeed by improving website visibility in search engines. Has the knowledge and skills to execute effective strategies that drive results. Loves potatoes (in every single form), dogs, and figure skating.",
        containerWidth: '39.013vw',
        containerHeight: '40.989vw',
        imageHeight: '29.583vw',
        imageWidth: '25.833vw',
        transform: 'rotate(-6.379deg)',
        transformHover: 'rotate(0deg)',
        captionWidth: '19.88vw',
        captionHeight: '13.338vw',
        backgroundColor: colors.hkw.orange[300],
        captionClipPathTransform: 'rotate(3.528deg)',
        captionClipPath: 'polygon(32% 0, 94% 11%, 100% 100%, 0 74%)',
        captionClipPathWidth: '19.88vw',
        captionClipPathHeight: '13.338vw',
        infoWidth: '10.278vw',
        color: colors.hkw.neutral.black,
        infoTransform: 'rotate(-3.528deg)',
    },
    { type: "testimonial", name: "Paula Mantle", role: "Marketing Director at Conviva", quote: "HKW felt like full-fledged members of my team.", color: colors.hkw.red[100], },
    { type: "testimonial", name: "Jonathan Birnbaum", role: "MExecutive Director at ISL", quote: "The whole HKW team was fantastic to work with!", color: colors.hkw.neutral.black, },
    { type: "cta-1" },
    {
        type: "staff",
        name: "Matt Grantski",
        role: "Developer",
        image: "matt.png",
        bio: "Web developer with over 15 years of experience, specializing in website and email development. Enjoys development for its strange balance between logic and art, two seemingly conflicting systems. Friend of cats; music, sports, and video game aficionado.",
        containerWidth: '35.469vw',
        containerHeight: '36.646vw',
        imageWidth: '24.564vw',
        imageHeight: '28.046vw',
        clipPath: 'polygon(52% 16%, 100% 3%, 98% 100%, 0 100%, 3% 0)',
        clipPathHover: 'polygon(50% 0%, 100% 0, 100% 100%, 0 100%, 0 0)',
        transform: 'rotate(-13.031deg)',
        transformHover: 'rotate(0deg)',
        captionHeight: '14.55vw',
        captionWidth: '16.98vw',
        backgroundColor: colors.hkw.blue[400],
        captionClipPathTransform: 'rotate(24.419deg)',
        captionClipPath: 'polygon(0 17%, 85% 0, 100% 80%, 10% 100%)',
        // captionClipPathWidth: '14.55vw',
        // captionClipPathHeight: '16.98vw',
        infoWidth: '10.279vw',
        color: colors.hkw.neutral.black,
        infoTransform: 'rotate(-24.419deg)',

    },
    { type: "testimonial", name: "Kevin Pedraja", role: "Partnew at Voxus PR", quote: "We communicate for a living, but HKW helped us crystalize our brand message.", color: colors.hkw.neutral.black, },
    { type: "testimonial", name: "Shomya Tripathy", role: "Director of Policy and Civic Engagement at Asian Counseling and Referral Service", quote: "Working with HKW was an incredible experience.", color: colors.hkw.neutral.white, },
    {
        type: "staff",
        name: "Harriet Cacdac",
        role: "Designer",
        bio: "Designer who firmly believes that great results come from collaboration and communication. She consistently helps businesses grow and achieve profitability. Full-time badminton player and part-time coffee drinker.",
        image: "harriet.png",
        containerWidth: '38.334vw',
        containerHeight: '38.362vw',
        imageWidth: '34.47vw',
        imageHeight: '31.832vw',
        transform: '',
        transformHover: 'rotate(0deg)',
        captionWidth: '20.139vw',
        captionHeight: '19.403vw',
        backgroundColor: colors.hkw.blue[400],
        captionClipPathTransform: 'rotate(65.903deg)',
        captionClipPath: 'polygon(100% 0, 80% 50%, 100% 100%, 0 100%, 0 0)',
        captionClipPathWidth: '14.236vw',
        captionClipPathHeight: '15.694vw',
        infoWidth: '13.542vw',
        color: colors.hkw.neutral.black,
        infoTransform: 'rotate(-65.903deg)',

    },
    { type: "testimonial", name: "John Bettencourt", role: "Oslo Coffee", quote: "HKW took our crude sketches and ideas and transformed them into something more than we imagined they could be.", color: colors.hkw.red[100], },
    { type: "testimonial", name: "Rhonda Walker", role: "CMO, ITRenew", quote: "Every marketing leader should have a partner like HKW.", color: colors.hkw.neutral.black, },
    {
        type: "staff",
        name: "Andrew Hughes",
        role: "Frontend Developer",
        bio: "Former stage and screen actor, now full-time web developer with a passion for creating visually appealing, user-friendly websites. Voracious reader and avid gardener with a newly discovered green thumb.",
        image: "andrew.png",
        containerWidth: '41.686vw',
        containerHeight: '42.307vw',
        imageWidth: '26.766vw',
        imageHeight: '28.331vw',
        transform: 'rotate(11.547deg)',
        transformHover: 'rotate(0deg)',
        captionWidth: '15.806vw',
        captionHeight: '16.831vw',
        backgroundColor: colors.hkw.blue[100],
        captionClipPathTransform: 'rotate(90deg)',
        captionClipPath: 'polygon(5% 15%, 85% 2%, 100% 86%, 18% 100%)',
        captionClipPathWidth: '15.806vw',
        captionClipPathHeight: '16.831vw',
        infoWidth: '13.542vw',
        color: colors.hkw.blue[500],
        infoTransform: 'rotate(-90deg)',
    },
    { type: "testimonial", name: "Emelyn Lybarger", role: "Outreach Coordinator at CELDF", quote: "HKW exceeded our expectations in their creative design and development of our branding, and in providing us with innovative web development and solutions.", color: colors.hkw.neutral.white, },
    {
        type: "staff",
        name: "Erick Doxey",
        role: "Photographer",
        image: "erick.png",
        containerWidth: '35.26vw',
        containerHeight: '36.644vw',
        imageWidth: '33.88vw',
        imageHeight: '34.493vw',
        transform: 'rotate(0deg)',
        transformHover: 'rotate(0deg)',
        captionWidth: '12.577vw',
        captionHeight: '12.577vw',
        backgroundColor: colors.hkw.yellow[300],
        captionClipPathTransform: 'rotate(32.684deg)',
        captionClipPath: 'polygon(100% 0, 100% 100%, 47% 82%, 0 98%, 0 0)',
        captionClipPathWidth: '12.577vw',
        captionClipPathHeight: '12.577vw',
        infoWidth: '13.542vw',
        color: colors.hkw.neutral.black,
        infoTransform: 'rotate(-32.684deg)',
    },
    { type: "cta-2" },
    //     {
    //         type: "staff",
    //         name: "Scott Mueller",
    //         role: "Partner",
    //         bio: "Strategist, designer, and project manager always looking for intuitive, elegant solutions. He’s designed everything from logos and brands to software, tangible products, and actual physical communities. Consummate hobbyist and enthusiastic reader and activist.",
    //         image: "scott.jpeg",
    //         containerWidth: '34.492vw',
    //         containerHeight: '32.862vw',
    //         imageWidth: '24.564vw',
    //         imageHeight: '28.046vw',
    //         transform: 'rotate(-13.031deg)',
    //         transformHover: 'rotate(0deg)',
    //         captionWidth: '209.552',
    //         captionHeight: '173.442',
    //         backgroundColor: colors.hkw.orange[300],
    //         captionClipPathTransform: 'rotate(24.419deg)',
    //         captionClipPath: 'polygon(0 17%, 83% 0, 100% 80%, 10% 100%)',
    //         captionClipPathHeight: '12.045vw',
    //         captionClipPathWidth: '14.552vw',
    //         infoWidth: '10.279vw',
    //         color: colors.hkw.neutral.white,
    //         infoTransform: 'rotate(-24.419deg)',
    //     },
    //     // {
    //     //     type: "trivia",
    //     //     text: "Celebrating 14 years in business!",
    //     //     index: 2,
    //     //     triviaWidth: "36.040vw",
    //     //     triviaHeight: "35.907vw",
    //     //     triviaLeft: "-9.028vw",
    //     //     triviaTop: "-0.347vw",
    //     //     triviaClipPath: "polygon(0 19%, 100% 0, 95% 91%, 30% 100%)",
    //     //     triviaClipPathWidth: '27.25vw',
    //     //     triviaClipPathHeight: '23.715vw',
    //     //     triviaClipPathTransform: 'rotate(42.67deg)',
    //     //     triviaBackgroundColor: colors.hkw.yellow[300],
    //     //     triviaTextWidth: '16.528vw',
    //     //     triviaTextTransform: 'rotate(-42.67deg)',
    //     //     triviaTextColor: colors.hkw.neutral.black,
    //     //     triviaTextTop: '9.722vw',
    //     //     triviaTextLeft: '6.944vw',

    //     // },
    //     // {
    //     //     type: "testimonial",
    //     //     name: "Melissa Huggins",
    //     //     role: "Executive Director at Spokane Arts",
    //     //     quote: "We can’t recommend HKW highly enough.",
    //     //     color: colors.hkw.blue[100],
    //     // },
    //     // {
    //     //     type: "staff",
    //     //     name: "Geneva Kaiser",
    //     //     role: "Partner",
    //     //     bio: "Frontend developer, designer, writer, and problem solver. Drinks too much coffee. Avid bicyclist, reader, and crafter.",
    //     //     image: "geneva.jpeg",
    //     //     containerWidth: '41.686vw',
    //     //     containerHeight: '42.307vw',
    //     //     imageWidth: '31.557vw',
    //     //     imageHeight: '32.706vw',
    //     //     transform: ' rotate(22.547deg)',
    //     //     transformHover: 'rotate(0deg)',
    //     //     captionWidth: '15.517vw',
    //     //     captionHeight: '15.517vw',
    //     //     backgroundColor: colors.hkw.blue[400],
    //     //     captionClipPathTransform: 'rotate(-64.139deg)',
    //     //     captionClipPath: 'polygon(0 0, 100% 0, 85% 50%, 100% 100%, 0 100%)',
    //     //     captionClipPathHeight: '11.614vw',
    //     //     captionClipPathWidth: ' 11.614vw',
    //     //     infoWidth: '10.279vw',
    //     //     color: colors.hkw.blue[100],
    //     //     infoTransform: 'rotate(64.139deg)',
    //     // },
]

export default aboutData
